### ISSUE TITLE
최종 점검 기능

### ISSUE THREAD

**Issue by J1miin** [OoChe/TobeBucket#53]
**버킷리스트 피드 열람**
- 친구 피드 선택
   - [x] 친구가 없는 경우  ‘아직 친구가 없어요.’라는 안내문을 표시 
   - [x] 친구가 작성한 공개 버킷이 없는 경우 ‘공개된 버킷이 없어요.’안내문 표시
  
**친구 버킷 조회하기**
- -[x] 친구가 작성한 버컷이 없는 경우 >> '친구가 공개한 작성된 버킷이 없어요' 안내문 표시

**버킷리스트 관리하기**
1. 버킷리스트 작성
- -[x] 버킷리스트 작성 완료 버튼 누른 경우 >> 버킷리스트가 추가되었습니다 내용 표시 후 나의 버킷 페이지로 리다이렉트
- -[x] 필수 항목 안채웠을 때 경고 
 
2. 버킷리스트 수정
- -[ ] 달성한 버킷리스트는 수정 >>  '카테고리, 함께하는 친구, 중간목표, 공개범위 수정, 세부설명만 수정 가능하다'는 안내를 표시

3. 버킷리스트 삭제
- -[x] 삭제하기 누른 경우 >> '삭제하시겠습니까?' 안내 화면에 표시
- -[x] 삭제된 후 버킷리스트 목록 화면으로 리다이렉트

**달성기록 남기기**
- -[x] stickerProcess에 따른 해제된 스티커 보여주기
- -[x] 날짜 설정 또는 스티커를 선택하지 않은 경우 >> '필수항목입니다' 안내 화면 표시 

**친구**
1. 친구 삭제하기
- -[x] 정말로 @@@님을 친구 목록에서 삭제하시겠어요? 표시

2. 친구 추가하기
- -[x] 친구의 아이디가 존재하지 않는 경우 >> '사용자가 존재하지 않습니다' 팝업 띄우기
- -[x] 친구 요청을 보낸 후 >> '친구 신청이 완료되었습니다' 문구 표시

3. 친구 요청 수락하기
- -[ ] 친구 요청을 받은 상대가 친구 요청을 거절한 경우 >> 사용자에게 '친구가 요청을 거절했어요ㅠㅠ' 표시 ❎

4. 친구 목록 조회하기
- -[x] 친구가 없는 경우 >> '친구 ID를 검색해서 추가해보세요' 문구 표시

**마이페이지**
1. 성취 데이터 조회
- -[x] 달성한 버킷리스트가 한 개도 없는 경우 >> '버킷 리스트를 달성해볼까요?' 표시
- -[x] 버킷리스트가 하나도 없는 경우 >> '버킷리스트를 추가해볼까요?' 표시

2. 사용자 정보 관리
- -[x] 이름 작성하지 않고 수정을 완료하는 경우 >> 이름은 필수로 작성해야한다는 안내 표시

**Comment by yewoonn** [comment]
**친구 추가하기**
- 친구가 아니며 친구 신청을 보내지 않은 친구에게 신청을 전송할 경우 (요청 전송됨을 표시)
- 친구 요청을 보내고 난 후, 다시 요청을 보낼 경우 (요청 완료임을 표시하고 버튼 비활성화)
- 검색한 친구 ID가 존재하지 않는 경우 (검색된 ID 없음을 표시)
- 친구 신청 보낼 사용자가 존재하지 않는 경우 (모든 사용자와 친구 상태이거나 친구 신청을 전송한 상태임을 표시)

**버킷 리스트 작성하기**
- 버킷리스트 항목을 올바르게 입력하는 경우 (버킷 리스트 추가 성공임을 표시)
- 필수 항목 중 입력이 안되는 경우 (입력되지 않은 항목 오류 창으로 표시)
- 중간 목표에 아무것도 입력되지 않는 경우 (공백 제외하여 DB 전달)
- 템플릿 사용 후 사용자가 수정하는 경우 (수정된 상태로 변경)
- 사용자가 작성 후 템플릿 가져오는 경우 (템플릿 정보로 변경)
- 지난 날짜에 대해 목표 달성 날짜 선택하는 경우 (선택하지 못하도록 설정)
